"""Swap-on-restart pattern: download new build, stage it, spawn a detached
batch script that waits for picasso.exe to exit, backs up the current
install, robocopies the staged build over it, and relaunches.

Why a separate process: Windows can't replace a running .exe — the file
is locked. The detached script outlives the parent and does the swap
once the parent has exited.

Why a batch file (not a Python script): the parent picasso.exe is
PyInstaller-packaged; child Python wouldn't have the bundled deps. cmd.exe
+ robocopy + powershell Compress-Archive are all already on Windows.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import urllib.request
import zipfile
from datetime import datetime
from pathlib import Path


def app_data_root() -> Path:
    """`%LOCALAPPDATA%\\Picasso` — backups, pending downloads, swap script.
    Created on first call. Falls back to ~/Picasso if LOCALAPPDATA isn't set."""
    base = os.environ.get("LOCALAPPDATA") or str(Path.home())
    p = Path(base) / "Picasso"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _install_dir() -> Path:
    """Directory containing picasso.exe in a frozen build."""
    if not getattr(sys, "frozen", False):
        raise RuntimeError(
            "Updater only works in a packaged build — sys.frozen is False. "
            "Run from a `dist/Picasso/picasso.exe` install."
        )
    return Path(sys.executable).parent


def _download(url: str, dest: Path) -> None:
    req = urllib.request.Request(url, headers={"User-Agent": "picasso-updater"})
    with urllib.request.urlopen(req, timeout=120) as r, open(dest, "wb") as f:
        shutil.copyfileobj(r, f)


def _extract(zip_path: Path, dest: Path) -> Path:
    """Extract `zip_path` into `dest`. If the zip has a single top-level
    folder (e.g. `Picasso/`), return that folder; otherwise return `dest`.
    The swap script copies *from* that returned path.
    """
    with zipfile.ZipFile(zip_path) as z:
        z.extractall(dest)
    entries = [p for p in dest.iterdir() if p.name != "__MACOSX"]
    if len(entries) == 1 and entries[0].is_dir():
        return entries[0]
    return dest


def perform_swap(download_url: str) -> Path:
    """Stage the new build and spawn a detached swap script.

    Caller (the FastAPI handler) should respond to the client and then
    arrange to exit shortly after this returns. The swap script sleeps
    long enough for a graceful shutdown.

    Returns the path to the spawned swap.bat for diagnostics.
    """
    install = _install_dir()
    appdata = app_data_root()
    pending = appdata / "pending"
    backups = appdata / "backups"
    if pending.exists():
        shutil.rmtree(pending, ignore_errors=True)
    pending.mkdir(parents=True)
    backups.mkdir(parents=True, exist_ok=True)

    # 1. Download and extract.
    zip_path = pending / "picasso.zip"
    _download(download_url, zip_path)
    staged = _extract(zip_path, pending)
    try:
        zip_path.unlink()
    except OSError:
        pass

    # 2. Generate the swap script. Inline paths — no need for variables in
    # cmd.exe on a one-shot run. Triple-backslash escape because Python
    # doubles backslashes inside the f-string written to disk.
    swap_bat = appdata / "swap.bat"
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_zip = backups / f"backup-{timestamp}.zip"

    swap_bat.write_text(_render_swap_bat(
        install=install,
        staged=staged,
        backup_zip=backup_zip,
        backups_dir=backups,
        pending_dir=pending,
    ), encoding="utf-8")

    # 3. Spawn detached so the parent can exit without taking the child down.
    DETACHED_PROCESS = 0x00000008
    CREATE_NEW_PROCESS_GROUP = 0x00000200
    subprocess.Popen(
        ["cmd", "/c", str(swap_bat)],
        creationflags=DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP,
        close_fds=True,
        cwd=str(appdata),
    )
    return swap_bat


def _render_swap_bat(
    *,
    install: Path,
    staged: Path,
    backup_zip: Path,
    backups_dir: Path,
    pending_dir: Path,
) -> str:
    return f"""@echo off
REM Picasso swap script — generated by perform_swap().
REM Lifecycle: parent exits → this runs detached → robocopy → relaunch.

echo Picasso updater: starting in 3 seconds...
ping -n 4 127.0.0.1 >nul

REM 1. Backup the current install (best-effort; never block the swap on a
REM    backup failure — robocopy is the recovery path of last resort).
echo Picasso updater: backing up current install...
powershell -NoProfile -Command "try {{ Compress-Archive -Path '{install}\\*' -DestinationPath '{backup_zip}' -Force; Write-Host '  backup OK' }} catch {{ Write-Host ('  backup skipped: ' + $_.Exception.Message) }}"

REM 2. Robocopy staged → install. /MIR mirrors (deletes stale files in
REM    the install that aren't in the new build) but /XD/XF guards user
REM    data and the install/update scripts.
echo Picasso updater: copying new files...
robocopy "{staged}" "{install}" /MIR /NFL /NDL /NP ^
    /XD batches source ^
    /XF imgproc.yaml install.bat update-alida.bat

REM 3. Trim old backups (keep last 3).
powershell -NoProfile -Command "Get-ChildItem -Path '{backups_dir}' -Filter 'backup-*.zip' | Sort-Object LastWriteTime -Descending | Select-Object -Skip 3 | Remove-Item -Force -ErrorAction SilentlyContinue"

REM 4. Clean up staging.
rmdir /S /Q "{pending_dir}" 2>nul

REM 5. Relaunch — single-instance probe in run_server() handles the case
REM    where the user has manually started picasso.exe in the meantime.
echo Picasso updater: relaunching...
start "" "{install}\\picasso.exe"

REM Self-delete (best effort; ignored if it fails).
del "%~f0" 2>nul
"""
